### ISSUE TITLE
RSpec 3 compatibility

### ISSUE THREAD

**Issue by liveh2o** [mmmries/rspec_rabl#13]
Specs fail spectacularly under RSpec 3. I'm guessing we're using a deprecated API:

```shell
Failure/Error: it { should render_attribute(:amount) }
NoMethodError:
  undefined method `object' for "v1/budgets/budget.rabl":String
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec_rabl-0.0.4/lib/rspec/rabl/attribute_matcher.rb:48:in `rendered_object'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec_rabl-0.0.4/lib/rspec/rabl/attribute_matcher.rb:64:in `collection?'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec_rabl-0.0.4/lib/rspec/rabl/attribute_matcher.rb:68:in `parsed_object'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec_rabl-0.0.4/lib/rspec/rabl/attribute_matcher.rb:52:in `attribute_rendered?'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec_rabl-0.0.4/lib/rspec/rabl/attribute_matcher.rb:19:in `matches?'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-expectations-3.0.4/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/memoized_helpers.rb:81:in `should'
# ./spec/views/v1/budget_views_spec.rb:24:in `block (3 levels) in <top (required)>'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:148:in `instance_exec'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:148:in `block in run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-rails-3.0.2/lib/rspec/rails/adapters.rb:72:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:430:in `block (2 levels) in run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
# ./spec/spec_helper.rb:60:in `block (2 levels) in <top (required)>'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:430:in `block (2 levels) in run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:432:in `run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:485:in `run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:303:in `with_around_example_hooks'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:145:in `run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:494:in `block in run_examples'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `map'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `run_examples'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:457:in `run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `block in run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `map'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block (2 levels) in run_specs'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `map'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:54:in `report'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:108:in `run_specs'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:86:in `run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/bin/rspec:23:in `load'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/bin/rspec:23:in `<main>'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/bin/ruby_executable_hooks:15:in `eval'
# /Users/ah/.rvm/gems/ruby-2.2.0@alfred/bin/ruby_executable_hooks:15:in `<main>'
```

Probably should get this figured out soon.

**Comment by mmmries** [comment]
I just ran all the specs for the gem under `rspec 3.2.0` and had no issues. The last [travis build](https://travis-ci.org/mmmries/rspec_rabl/jobs/51887649#L124) also ran under rspec 3.2.0.

I'll try locking down to 3.0.4 locally to see if I can replicate

**Comment by liveh2o** [comment]
I upgraded to 3.2 initially and had the same problem. I also tried using the new `expect` syntax, and that didn't work either.

**Comment by mmmries** [comment]
it looks like the line it is failing at is calling `subject.object`, normally the subject gets set by the `RSpec::Rabl::ExampleGroup` mixin. Can you send me a link the branch you are working on in alfred and I can take a deeper look?

**Comment by liveh2o** [comment]
Turns out, this is a duplicate of #10, though contains more docs. Closing it.
